name: Generate sitemap/rss/robots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sitemap.xml, rss.xml, robots.txt
        shell: pwsh
        run: |
          pwsh -File "build.ps1" -SiteUrl "https://baner-ai.vercel.app" -OutputDir "."

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "sitemap.xml rss.xml robots.txt"
          message: "chore: auto-generate sitemap/rss/robots"
          default_author: github_actions
